### ISSUE TITLE
无法下载在线脚本，以及无法保存设置

### ISSUE THREAD

**Issue by PackageInstaller** [Hicores/QTool#1]
报错是java.io.FileNotFoundException:/storage...开头的一个Toast

**Comment by PackageInstaller** [comment]
厂商:google

版本:Pixel 5

主板:lmi

设置参数:redfin

硬件识别码：google/redfin/redfin:12/SP2A.220405.003/8210211:user/release-keys

TIME:1649936224000

Build标签:release-keys

USER:akito

ID:SP2A.220405.004

RELEASE:12

SDK_INT:32

MANUFACTURER:Google

HOST:haruka-sgp-01

TYPE:user

CODENAME:REL

cpu指令集:arm64-v8a

RADIO:unknown

**Comment by PackageInstaller** [comment]
模块版本是QTool-0.0.5-CI-254(4)

**Comment by PackageInstaller** [comment]
QQ版本：8.8.85

**Comment by Hicores** [comment]
设置-辅助功能-QTool基础设置 更改存储目录,重新换一个配置目录

**Comment by PackageInstaller** [comment]
感谢，解决了
