### ISSUE TITLE
如何打包apk

### ISSUE THREAD

**Issue by dongfangbotao** [Hicores/QTool#11]
我好像不会使用github

**Comment by lyz410482** [comment]
> 我好像不会使用github

**Comment by Hicores** [comment]
> 同问，编译一直各种报错，请问作者大大用的什么ide啊？

Android Studio
直接用git整个项目clone下来,记得clone子项目,不要直接点击网页下载zip,然后打开,直接菜单Build

**Comment by genhao3** [comment]
> > 同问，编译一直各种报错，请问作者大大用的什么ide啊？
> 
> Android Studio 直接用git整个项目clone下来,记得clone子项目,不要直接点击网页下载zip,然后打开,直接菜单Build

子项目是指？
