### ISSUE TITLE
最新版QQNT架构版本8.9.63的QT部分功能失效

### ISSUE THREAD

**Issue by Buzaijun** [Hicores/QTool#17]
![Screenshot_2023-07-04-18-58-12-918_com.tencent.mobileqq.jpg](https://github.com/Hicores/QTool/assets/41782514/3863f573-fff3-44c5-9bff-bcf4b1bcb490)

![Screenshot_2023-07-04-18-58-30-550_com.tencent.mobileqq.jpg](https://github.com/Hicores/QTool/assets/41782514/c6252aa1-f952-4b34-9e13-94bd33695561)

![Screenshot_2023-07-04-18-58-39-230_com.tencent.mobileqq.jpg](https://github.com/Hicores/QTool/assets/41782514/118b2a21-d5bb-47af-baab-b6297debb3c2)

![Screenshot_2023-07-04-18-58-44-310_com.tencent.mobileqq.jpg](https://github.com/Hicores/QTool/assets/41782514/c5d63358-99b9-4911-9dd6-cb42806f01a7)

**Comment by Hicores** [comment]
使用QQNT以下的版本8.9.58和以下,或者换用其他同类型模块
