### ISSUE TITLE
QQ8.9.71完全失效？

### ISSUE THREAD

**Issue by dhy0302** [Hicores/QTool#18]
Qtool已经正常添加到QQ（如图1）。而且QQ8.9.71版本在第1次启动Qtool时，可以正常选择储存文件仓库，但是在设置里面找不到入口（如图2）。![Screenshot_2023-08-01-21-05-25-819_org.lsposed.lspatch.jpg](https://github.com/Hicores/QTool/assets/106533947/db707b7c-2756-4fd5-91b7-b874515ba9c7)

![Screenshot_2023-08-01-21-05-09-096_com.tencent.mobileqq.jpg](https://github.com/Hicores/QTool/assets/106533947/775d1a18-fdf0-459f-8951-aee7b25516b0)

真的很喜欢Qtool模块，这个模块可以通过添加脚本实现很多功能。

好希望开发者能适配一下NT版本的QQ🙏🙏🙏

**Comment by Hicores** [comment]
由于模块较为复杂,作者不打算适配了,有技术的可以选择自行适配,或者保持旧版本QQ进行使用,或者换用其他模块
