### ISSUE TITLE
338版本及340版本无限闪退。

### ISSUE THREAD

**Issue by hkcnjd** [Hicores/QTool#2]
设备:三星s22u
系统:Android12
qq版本8.8.88
未root，使用的无极阴，版本9.0.1
自从前两天更新338版本后，进去qq主界面之后，点击任何聊天窗口界面就会闪退。即使关闭所有模块功能也这样。
尝试过只启用qt这一个模块也会这样。

如果可以修复最好了，没法修复也没什么。
我猜测估计是太极的问题，wushu大佬估计也不会有时间去搞太极了。
以后可能免root就只能用lspatch了。

最后感谢作者的辛苦付出，非常喜欢这个插件的qq语音包功能。

再次感谢，如有打扰还请见谅。

**Comment by Hicores** [comment]
抓一份Logcat日志

**Comment by Hicores** [comment]
@hkcnjd 只开启其他模块,会不会有闪退的情况

**Comment by hkcnjd** [comment]
> 抓一份Logcat日志

大佬我不会啊，可以说一下怎么抓吗？

**Comment by hkcnjd** [comment]
> @hkcnjd 只开启其他模块,会不会有闪退的情况

不会，只要启用了qt，在点击任何聊天窗口的选项就会闪退。
没更新338之前有搭配qa，color一起使用，没任何问题。
