### ISSUE TITLE
关于易拉钩的支持问题？

### ISSUE THREAD

**Issue by PaienNate** [Hicores/QTool#3]
如题，天鉴有一个易拉钩(SPromoter)模块，用法大概是：

1. 对软件打包，内嵌易拉钩模块
2. 安装打包后软件，并运行易拉钩程序
3. 在易拉钩内，选择要生效的Xposed模块
4. 启动软件，可看到对应的模块生效（即使软件未内置该模块）

因为最近多了一个lspatch软件，可以用来打包插件，但是由于是早期版本，不支持选择作用域，所以我尝试了一下用lspatch打包易拉钩，让易拉钩作为"作用域选择器"，测试QA和QQ瘦身均能正常运行，而尝试QTool时，QQ无任何反应（表现为模块未加载），再次使用lsposed直接注入QTool插件时正常。

并不清楚这些操作背后对应的具体原理，且易拉钩/lspatch并没有以及尚未完成日志功能，所以请问是否其有可能予以支持？若可以支持，是否需要我提供什么环境？

另：因为这个打包方式极其冷门，所以我可能给您制造了无用的问题，如有打扰造成不必要麻烦，提前向您致歉。

**Comment by Hicores** [comment]
fix in 6bb0f5c096e2e07d97873cf017154012801d8459
