### ISSUE TITLE
发送音乐异常

### ISSUE THREAD

**Issue by Termux000001** [Hicores/QTool#7]
![Screenshot_2022-07-10-08-55-08-139_com tencent mobileqq](https://user-images.githubusercontent.com/67861307/178127300-feefdf10-7c39-4e31-a792-929f2e2ed1dc.png)
本地点歌脚本，发送音乐会同时发送文件路径，是脚本问题还是qt问题😂

**Comment by Hicores** [comment]
你脚本问题
